### ISSUE TITLE
Add OML Graphical Syntax section to the OML Specification

### ISSUE THREAD

**Issue by melaasar** [opencaesar/oml#42]
## User Story
As an OML modeler, I would like to get documentation on OML graphical notation in the OML specification.

## Detailed Description
We will use the [draw.io](https://draw.io/) tool to create the OML notation templates and store the project file as well as the SVG files in github (under spec/src). We will include hyperlinks in the SVG to other sections of the OML spec.

## Acceptance Criteria
- [ ] OML spec has information on the OML notation
   - [x] Vocabulary: Box(«vocabulary» IRI, Aspect*, Concept*, RelationEntity8, Structure*, FacetedScalar*, EnumeratedScalar*, AnnotationProperty*, Rule*)
   - [x] Aspect: Box(«aspect» ID | ScalarProperty* | StructuredProperty*)
   - [x] Concept: Box(«concept» ID | ScalarProperty* | StructuredProperty*)
   - [x] RelationEntity: Box(«relation entity» ID | ForwardRelation ReverseRelation | ScalarProperty* | StructuredProperty*) & Line(source to relation) & LineWithOpenArrow(relation to target)
   - [x] Structure: Box(«structure» ID | ScalarProperty* | StructuredProperty*)
   - [x] FacetedScalar: Box(«scalar» ID)
   - [x] EnumeratedScalar: Box(«enumerated scalar» ID | Literal*)
   - [x] ScalarProperty: Label(ID : range)
   - [x] StructuredProperty: Label(ID : range)
   - [x] AnnotationProperty: Box(«annotation» ID)
   - [x] ForwardRelation: Label(«forward» ID)
   - [x] ReverseRelation: Label(«reverse» ID)
   - [x] Rule: Box(«rule» ID | Antecedent* | Consequent*)
   - [x] Predicate: Label:(same as textual syntax)
- [x] A section added to the concrete syntax common section that describe the notational conventions used

Note: "|" means a compartment separator, and each compartment has a centered title in the top.
Note: All compartments should be optional with ? symbol.

## Sub-task List
- [x] Generate diagrams with Draw.io
- [x] Include hyperlinks in the diagrams
- [x] Create template or boilerplate to easily include and edit diagrams in the spec
